language:      node_js
git:
  depth:       3
node_js:
  - "node"
before_install:
  - yarn -v
install: yarn --frozen-lockfile --non-interactive
script:
  - yarn test
  - yarn prod
cache:
  directories:
    - node_modules
  yarn: true
notifications:
  email: false
