language: node_js
git:
  depth: 3
node_js:
  - "node"
install: yarn --frozen-lockfile --non-interactive
script:
  - yarn prod
cache:
  directories:
    - node_modules
  yarn: true
notifications:
  email: false
